if (typeof importScripts === "function") importScripts("api.js");
const RESULT_TYPE = "BRIDGECART_CART_RESULT";
const orderCaptureFrames = new Map();
// The panel is global to the Chrome window, so it stays open while the admin
// switches between the queue, 1688 product tabs, and provider-order tabs.
function enablePersistentSidePanel() {
  // Keep the worker usable on an older Chrome build, where the manifest may
  // still be loaded from a previous extension version but sidePanel is absent.
  const sidePanel = globalThis.chrome && chrome.sidePanel;
  if (!sidePanel || typeof sidePanel.setPanelBehavior !== "function") return;
  try {
    const result = sidePanel.setPanelBehavior({ openPanelOnActionClick: true });
    if (result && typeof result.catch === "function") result.catch((error) => console.error("[BridgeCart][worker] Could not enable the side panel", error));
  } catch (error) {
    console.error("[BridgeCart][worker] Could not enable the side panel", error);
  }
}
enablePersistentSidePanel();
class ReadinessError extends Error { constructor(code, message) { super(message); this.code = code; } }
const taskKey = (task) => task?.purchaseTaskId || task?.orderItemId;
function log(step, extra = {}) { console.info("[BridgeCart][worker]", { step, ...extra }); }
function offerIdFromUrl(value) { try { const url = new URL(value); if (!(url.hostname === "1688.com" || url.hostname.endsWith(".1688.com"))) return null; return url.searchParams.get("offerId") || url.searchParams.get("id") || url.pathname.match(/^\/offer\/(\d+)\.html/i)?.[1] || url.pathname.match(/(\d+)\.html/)?.[1] || null; } catch { return null; } }
function normalizeOfferId(value) { return String(value ?? "").replace(/^abb-/i, "").trim(); }
function isExpectedProductUrl(url, providerItemId) { const offerId = offerIdFromUrl(url); return Boolean(offerId && normalizeOfferId(offerId) === normalizeOfferId(providerItemId)); }
function isSupportedOrderPageUrl(value) { try { const url = new URL(value), path = url.pathname.toLowerCase(), is1688 = url.hostname === "1688.com" || url.hostname.endsWith(".1688.com"), isBuyerOrderList = url.hostname === "air.1688.com" && /\/trade-order-list\/buyer-order-list\.html$/.test(path), isBuyerOrderDetail = url.hostname === "air.1688.com" && /\/trade-order-detail\/index\.html$/.test(path), hasOrderId = ["orderId", "tradeId", "order_id", "trade_id", "orderNo", "order_no"].some((key) => url.searchParams.has(key)), isOrderPath = /(?:^|\/)(?:order|trade)[_\/-]/.test(path) || /order[_-]?(?:detail|success|pay|confirm)/.test(path); return isBuyerOrderList || (isBuyerOrderDetail && hasOrderId) || (is1688 && (isOrderPath && (hasOrderId || /(?:detail|success|pay|confirm)/.test(path)))); } catch { return false; } }
async function saveState(key, state) { const { cartPreparationStates = {} } = await chrome.storage.local.get("cartPreparationStates"), previous = cartPreparationStates[key] || {}; await chrome.storage.local.set({ cartPreparationStates: { ...cartPreparationStates, [key]: { ...previous, ...state, task: state.task || previous.task } } }); }
async function persistCartResult(payload) { if (!payload?.purchaseTaskId || typeof globalThis.extensionApiFetch !== "function" || !["cart-added", "needs-review", "failed"].includes(payload.state)) return; const response = await globalThis.extensionApiFetch("/api/extension/purchase-cart-result", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ purchaseTaskId: payload.purchaseTaskId, cartAdded: payload.state === "cart-added", message: payload.message || payload.code || "Cart preparation requires review.", skuResults: payload.skuResults || [] }) }); if (!response.ok) throw new Error("The cart result could not be persisted."); }
async function waitForExpectedContent(tabId, providerItemId, timeoutMs = 25000) { const deadline = Date.now() + timeoutMs; let attempt = 0, lastUrl = "", sawSupportedProductUrl = false; while (Date.now() < deadline) { attempt += 1; let tab; try { tab = await chrome.tabs.get(tabId); } catch { throw new ReadinessError("PRODUCT_PAGE_NAVIGATION_FAILED", "The expected 1688 product page did not open."); } const url = tab.url || ""; if (url !== lastUrl) { lastUrl = url; log("navigation", { tabId, url, attempt }); } const observedOfferId = offerIdFromUrl(url); if (observedOfferId && !isExpectedProductUrl(url, providerItemId)) throw new ReadinessError("PRODUCT_PAGE_NAVIGATION_FAILED", "The expected 1688 product page did not open."); if (isExpectedProductUrl(url, providerItemId)) { sawSupportedProductUrl = true; try { const response = await chrome.tabs.sendMessage(tabId, { type: "BRIDGECART_PING" }); if (response?.ready && (response.documentReadyState === "interactive" || response.documentReadyState === "complete")) return; } catch {} } await new Promise((resolve) => setTimeout(resolve, 400)); } if (!sawSupportedProductUrl) throw new ReadinessError("PRODUCT_PAGE_NAVIGATION_FAILED", "The expected 1688 product page did not open."); throw new ReadinessError("CONTENT_SCRIPT_NOT_READY", "BridgeCart could not connect to the 1688 page."); }
async function startPreparation(task) { const key = taskKey(task); await saveState(key, { state: "opened", message: "Opening original 1688 product page…" }); const tab = await chrome.tabs.create({ url: task.productUrl, active: true }); await saveState(key, { state: "waiting-for-page", message: "Waiting for the 1688 page…" }); await waitForExpectedContent(tab.id, task.providerItemId); const finalTab = await chrome.tabs.get(tab.id); if (!isExpectedProductUrl(finalTab.url || "", task.providerItemId)) throw new ReadinessError("PRODUCT_PAGE_NAVIGATION_FAILED", "The expected 1688 product page did not open."); const response = await chrome.tabs.sendMessage(tab.id, { type: "BRIDGECART_PREPARE_CART", payload: task }); if (["PRICE_CHANGED", "PRICE_CHANGED_AGAIN"].includes(response?.code)) await saveState(key, { ...response, tabId: tab.id }); }
async function approvePriceOverride(task, priceLines) { const key = taskKey(task), { cartPreparationStates = {} } = await chrome.storage.local.get("cartPreparationStates"), review = cartPreparationStates[key]; if (!review || !["PRICE_CHANGED", "PRICE_CHANGED_AGAIN"].includes(review.code)) throw new ReadinessError("PRICE_REVIEW_NOT_FOUND", "This price review is no longer available. Prepare the product again."); const tabId = review.tabId, tab = await chrome.tabs.get(tabId); if (!Number.isInteger(tabId) || !isExpectedProductUrl(tab.url || "", task.providerItemId)) throw new ReadinessError("PRODUCT_PAGE_NAVIGATION_FAILED", "The reviewed tab is no longer the expected 1688 product page."); await waitForExpectedContent(tabId, task.providerItemId); await chrome.tabs.sendMessage(tabId, { type: "BRIDGECART_PRICE_OVERRIDE", payload: { task, priceOverride: { priceLines } } }); }
async function captureFrameIds(tabId) { const known = [0, ...(orderCaptureFrames.get(tabId) || [])]; try { const frames = await chrome.webNavigation?.getAllFrames?.({ tabId }) || []; for (const frame of frames) if (frame.frameId !== undefined && (/^https:\/\/(?:[^/]+\.)?1688\.com\//i.test(frame.url || "") || frame.url === "about:blank")) known.push(frame.frameId); } catch {} return [...new Set(known)]; }
async function waitForOrderContent(tabId, timeoutMs = 8000) { const deadline = Date.now() + timeoutMs; while (Date.now() < deadline) { const tab = await chrome.tabs.get(tabId); if (!isSupportedOrderPageUrl(tab.url || "")) throw new ReadinessError("ORDER_PAGE_NOT_SUPPORTED", "Open the 1688 draft, buyer order list, order-detail, or order-success page first."); for (const frameId of await captureFrameIds(tabId)) { try { if ((await chrome.tabs.sendMessage(tabId, { type: "BRIDGECART_PING" }, { frameId }))?.ready) return; } catch {} } await new Promise((resolve) => setTimeout(resolve, 400)); } throw new ReadinessError("CONTENT_SCRIPT_NOT_READY", "BridgeCart could not connect to this 1688 order page. Reload the page and try again."); }
async function captureProviderOrder(queueItems) { const [tab] = await chrome.tabs.query({ active: true, currentWindow: true }); if (!tab?.id || !isSupportedOrderPageUrl(tab.url || "")) throw new ReadinessError("ORDER_PAGE_NOT_SUPPORTED", "Open the 1688 draft, buyer order list, order-detail, or order-success page first."); await waitForOrderContent(tab.id); let lastResponse; for (const frameId of await captureFrameIds(tab.id)) { try { const response = await chrome.tabs.sendMessage(tab.id, { type: "BRIDGECART_CAPTURE_PROVIDER_ORDER", payload: { queueItems } }, { frameId }); if (response?.ok) return response; if (response && (!lastResponse || response.frameUrl !== "about:blank")) lastResponse = response; } catch {} } return lastResponse || { ok: false, code: "ORDER_NOT_DETECTED", message: "1688 order content was not detected in this page or its embedded frames." }; }
async function captureProviderTracking() { const [tab] = await chrome.tabs.query({ active: true, currentWindow: true }); if (!tab?.id || !isSupportedOrderPageUrl(tab.url || "")) throw new ReadinessError("ORDER_PAGE_NOT_SUPPORTED", "Open the 1688 buyer order-detail page first."); await waitForOrderContent(tab.id); for (const frameId of await captureFrameIds(tab.id)) { try { const response = await chrome.tabs.sendMessage(tab.id, { type: "BRIDGECART_CAPTURE_PROVIDER_TRACKING" }, { frameId }); if (response?.ok && response.frameUrl !== "about:blank") return response; } catch {} } return { ok: false, code: "ORDER_NOT_DETECTED", message: "1688 order tracking content was not detected." }; }
chrome.runtime.onMessage.addListener((message, sender, sendResponse) => { if (message?.type === "BRIDGECART_CONTENT_READY" && sender.tab?.id !== undefined) { const frames = new Set(orderCaptureFrames.get(sender.tab.id) || []); frames.add(sender.frameId || 0); orderCaptureFrames.set(sender.tab.id, [...frames]); return; } if (message?.type === "BRIDGECART_START_PREPARATION") { startPreparation(message.payload).then(() => sendResponse({ accepted: true })).catch(async (error) => { const task = message.payload, payload = { purchaseTaskId: task.purchaseTaskId, orderItemId: task.orderItemId, skuResults: (task.skus || [task]).map((sku) => ({ orderItemId: sku.orderItemId, prepared: false })), state: "failed", code: error.code || "OPEN_OR_PREPARE_FAILED", message: error.message || "Could not open or prepare the 1688 page." }; await saveState(taskKey(task), payload); await persistCartResult(payload).catch(() => {}); sendResponse({ accepted: false, code: payload.code }); }); return true; } if (message?.type === "BRIDGECART_APPROVE_PRICE_OVERRIDE") { approvePriceOverride(message.payload.item, message.payload.priceLines).then(() => sendResponse({ accepted: true })).catch(async (error) => { await saveState(taskKey(message.payload.item), { state: "needs-review", code: error.code || "PRICE_OVERRIDE_FAILED", message: error.message || "The approved prices could not be revalidated." }); sendResponse({ accepted: false, code: error.code }); }); return true; } if (message?.type === "BRIDGECART_CAPTURE_PROVIDER_ORDER") { captureProviderOrder(message.payload?.queueItems || []).then(sendResponse).catch((error) => sendResponse({ ok: false, code: error.code || "ORDER_NOT_DETECTED", message: error.message })); return true; } if (message?.type === RESULT_TYPE && (message.payload?.purchaseTaskId || message.payload?.orderItemId)) { const payload = { ...message.payload, tabId: sender.tab?.id }; saveState(taskKey(payload), payload); persistCartResult(payload).catch((error) => saveState(taskKey(payload), { ...payload, state: "needs-review", code: "CART_RESULT_SAVE_FAILED", message: error.message })); } });
chrome.runtime.onMessage.addListener((message, _sender, sendResponse) => { if (message?.type !== "BRIDGECART_CAPTURE_PROVIDER_TRACKING") return; captureProviderTracking().then(sendResponse).catch((error) => sendResponse({ ok: false, code: error.code || "ORDER_NOT_DETECTED", message: error.message })); return true; });
