const output = document.getElementById("notice"), credentialInput = document.getElementById("credential"), connectionState = document.getElementById("connectionState"), queueElement = document.getElementById("queue"), captureElement = document.getElementById("capture");
let queue = [], states = {}, capturedOrder = null;
const formatCny = (value) => `¥${Number(value ?? 0).toFixed(2)}`;
const shortId = (value) => String(value || "").slice(0, 8);
const selectedAttributes = (sku) => Object.entries(sku.attributes || {}).map(([key, value]) => `${key}: ${value}`).join(" · ") || sku.skuLabel || "Variant not provided";
const taskKey = (task) => task.purchaseTaskId || task.orderItemId;
async function renderConnectionState() { const { extensionCredential } = await chrome.storage.local.get("extensionCredential"); connectionState.textContent = extensionCredential ? "Connected as purchasing admin" : "Not connected"; }
async function saveState(key, state) { states[key] = state; await chrome.storage.local.set({ cartPreparationStates: states }); renderQueue(); }
function renderQueue() { queueElement.replaceChildren(); for (const task of queue) { const state = states[taskKey(task)] || { state: task.taskState === "needs_review" ? "needs-review" : "waiting", message: task.blockReason || "" }, card = document.createElement("article"), image = document.createElement("img"), content = document.createElement("div"), title = document.createElement("strong"), details = document.createElement("div"), badge = document.createElement("span"), message = document.createElement("div"), prepare = document.createElement("button"); card.className = "item"; image.className = "image"; image.alt = ""; image.src = task.productImage || "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='58' height='58'/%3E"; title.textContent = `${task.productTitle || "Product"} · ${task.orderNumber || shortId(task.productOrderId)}`; details.className = "meta"; details.textContent = task.skus.map((sku) => `${selectedAttributes(sku)}\nQty ${sku.quantity} · Expected ${formatCny(sku.expectedUnitPriceCny)}`).join("\n\n"); badge.className = `status ${state.state}`; badge.textContent = task.canPrepare ? state.state : "blocked"; message.className = "meta"; message.textContent = task.blockReason || (state.priceLines?.length ? state.priceLines.map((line) => `SKU ${shortId(line.orderItemId)}: Expected ${formatCny(line.expectedPrice)} · Current ${formatCny(line.currentPrice)}`).join("\n") : (state.message || "")); prepare.textContent = state.state === "waiting" ? "Open / Prepare product on 1688" : "Open / Prepare again"; prepare.disabled = !task.canPrepare; prepare.addEventListener("click", () => openAndPrepare(task)); content.append(title, details, badge, message); if (task.canPrepare && ["PRICE_CHANGED", "PRICE_CHANGED_AGAIN"].includes(state.code)) { const actions = document.createElement("div"), approve = document.createElement("button"), cancel = document.createElement("button"); actions.className = "actions"; approve.textContent = "Add all approved SKUs"; cancel.textContent = "Cancel"; cancel.className = "secondary"; approve.addEventListener("click", () => approvePriceOverride(task, state)); cancel.addEventListener("click", () => saveState(taskKey(task), { ...state, state: "needs-review", code: "PRICE_REVIEW_CANCELLED", message: "Price review cancelled. No cart action was taken." })); actions.append(approve, cancel); content.append(actions); } content.append(prepare); card.append(image, content); queueElement.append(card); } if (!queue.length) queueElement.textContent = "No queued purchase products."; }
async function loadQueue() { output.textContent = "Loading purchase queue…"; try { const response = await extensionApiFetch("/api/extension/purchase-queue"), payload = await response.json(); if (!response.ok) throw new Error(payload?.error?.message || "Purchase queue could not be loaded."); queue = Array.isArray(payload.data) ? payload.data.filter((task) => task.provider === "alibaba1688") : []; output.textContent = queue.length ? `${queue.length} queued product${queue.length === 1 ? "" : "s"} loaded.` : "No queued purchase products."; renderQueue(); } catch (error) { queue = []; renderQueue(); output.textContent = error.message || "Purchase queue could not be loaded."; } }
async function openAndPrepare(task) { if (!/^https:\/\/(?:[^/]+\.)?1688\.com\//i.test(task.productUrl)) return saveState(taskKey(task), { state: "needs-review", code: "UNSUPPORTED_URL", message: "Only the original 1688 product URL can be prepared." }); await saveState(taskKey(task), { state: "opened", message: "Opening original 1688 product page…" }); try { await chrome.runtime.sendMessage({ type: "BRIDGECART_START_PREPARATION", payload: task }); } catch (error) { await saveState(taskKey(task), { state: "failed", code: "OPEN_OR_PREPARE_FAILED", message: error.message || "Could not open or prepare the 1688 page." }); } }
async function approvePriceOverride(task, review) { try { const response = await chrome.runtime.sendMessage({ type: "BRIDGECART_APPROVE_PRICE_OVERRIDE", payload: { item: task, priceLines: review.priceLines } }); if (!response?.accepted) throw new Error("The approved prices could not be revalidated."); } catch (error) { await saveState(taskKey(task), { state: "needs-review", code: "PRICE_OVERRIDE_FAILED", message: error.message || "The approved prices could not be revalidated." }); } }
function flattenedQueueItems() { return queue.flatMap((task) => task.skus.map((sku) => ({ ...sku, purchaseTaskId: task.purchaseTaskId, purchaseBatchId: task.purchaseBatchId, providerItemId: task.providerItemId }))); }
async function captureProviderOrder() { output.textContent = "Capturing the current 1688 order for review…"; try { const response = await chrome.runtime.sendMessage({ type: "BRIDGECART_CAPTURE_PROVIDER_ORDER", payload: { queueItems: flattenedQueueItems() } }); if (!response?.ok) throw new Error(response?.message || "1688 order could not be captured."); capturedOrder = response; output.textContent = "Provider capture is retained for compatibility and will move to admin review in Phase 4."; captureElement.textContent = `${response.matches.length} provider lines captured.`; } catch (error) { output.textContent = error.message || "1688 order could not be captured."; } }
document.getElementById("connect").addEventListener("click", async () => { const token = credentialInput.value.trim(); if (!token) { output.textContent = "Paste a credential issued by an admin first."; return; } await chrome.storage.local.set({ extensionCredential: token }); credentialInput.value = ""; await loadQueue(); await renderConnectionState(); });
document.getElementById("disconnect").addEventListener("click", async () => { await chrome.storage.local.remove("extensionCredential"); queue = []; renderQueue(); await renderConnectionState(); }); document.getElementById("refresh").addEventListener("click", loadQueue); document.getElementById("captureOrder").addEventListener("click", captureProviderOrder);
chrome.runtime.onMessage.addListener((message) => { if (message?.type === "BRIDGECART_CART_RESULT") saveState(message.payload.purchaseTaskId || message.payload.orderItemId, message.payload); }); chrome.storage.onChanged.addListener((changes, areaName) => { if (areaName === "local" && changes.cartPreparationStates) { states = changes.cartPreparationStates.newValue || {}; renderQueue(); } });
(async () => { ({ cartPreparationStates: states = {} } = await chrome.storage.local.get("cartPreparationStates")); await renderConnectionState(); const { extensionCredential } = await chrome.storage.local.get("extensionCredential"); if (extensionCredential) await loadQueue(); else renderQueue(); })();
