"use client";

import { ChevronDown, ChevronUp, RefreshCw } from "lucide-react";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { Alert, Badge, Button, Card, LoadingState, PageHeader, PriceDisplay, ProductThumbnail, StatusBadge } from "@/components/ui";
import { buttonClasses } from "@/components/ui/button";
import type { OrderStatus } from "@/lib/domain/types";

type CostState = "actual" | "estimated" | "partial" | "unavailable";
type SkuLine = { orderItemId: string; skuLabel: string; attributes: Record<string, string>; quantity: number; status: OrderStatus; costState: CostState; supplierAmountCny: number | null; localDeliveryCny: number | null; weightKg: number | null; guangzhouCostCny: number | null; serviceChargeCny: number | null; bangladeshShippingBdt: number | null; totalBdt: number | null; exchangeRate: number | null; note: string | null };
type Submission = { productOrderId: string; orderNumber: string; submittedAt: string; status: OrderStatus; totalQuantity: number; productAmountCny: number | null; localDeliveryCny: number | null; totalWeightKg: number | null; guangzhouCostCny: number | null; serviceChargeCny: number | null; bangladeshShippingBdt: number | null; totalBdt: number | null; costState: CostState; skuLines: SkuLine[] };
export type ProductStatementDetail = { product: { productLinkId: string; productCode: string | null; title: string | null; images: string[]; category: string | null }; aggregate: Omit<Submission, "productOrderId" | "orderNumber" | "submittedAt" | "skuLines"> & { mixedProgress: boolean; note: string | null }; submissions: Submission[] };

export function ClientProductStatementDetail({ productLinkId, fixtureData }: { productLinkId: string; fixtureData?: ProductStatementDetail }) {
  const [detail, setDetail] = useState<ProductStatementDetail | undefined>(fixtureData);
  const [loading, setLoading] = useState(!fixtureData);
  const [error, setError] = useState<string>();
  const load = useCallback(async (signal?: AbortSignal) => {
    if (fixtureData) { setDetail(fixtureData); setLoading(false); return; }
    setLoading(true); setError(undefined);
    try { const response = await fetch(`/api/client/product-statement/${productLinkId}`, { signal, cache: "no-store" }); const payload = await response.json().catch(() => ({})) as { data?: ProductStatementDetail; error?: { message?: string } }; if (!response.ok || !payload.data) throw new Error(payload.error?.message || "Product statement detail could not be loaded."); setDetail(payload.data); } catch (cause) { if ((cause as Error).name !== "AbortError") setError(cause instanceof Error ? cause.message : "Product statement detail could not be loaded."); } finally { if (!signal?.aborted) setLoading(false); }
  }, [fixtureData, productLinkId]);
  useEffect(() => { const controller = new AbortController(); void load(controller.signal); return () => controller.abort(); }, [load]);
  if (loading && !detail) return <LoadingState label="Loading product statement detail" />;
  if (error || !detail) return <Card className="p-5 shadow-panel"><Alert variant="danger" title="Product statement unavailable">{error || "This product statement is unavailable."}<Button variant="outline" size="sm" onClick={() => void load()} className="mt-3"><RefreshCw className="h-4 w-4" />Try again</Button></Alert></Card>;
  const aggregate = detail.aggregate;
  return <div className="space-y-6 pb-24 lg:pb-0"><PageHeader eyebrow="Product statement" title={detail.product.title || "Product statement detail"} description="Every submission and SKU for this product link. Monetary values retain their saved estimate or actual state." actions={<Link href="/client/excel-details" className={buttonClasses({ variant: "outline", size: "md" })}>Back to statement</Link>} /><Card className="overflow-hidden shadow-panel"><div className="flex flex-wrap items-start gap-4 border-b border-border bg-surface-muted p-5"><ProductThumbnail src={detail.product.images[0]} alt={detail.product.title || "Product"} size="xl" /><div className="min-w-0 flex-1"><p className="text-xs font-bold uppercase tracking-[0.1em] text-muted">{detail.product.category || "Uncategorized"}</p><p className="mt-2 font-mono text-xs text-muted">{detail.product.productCode || "Product code unavailable"}</p><div className="mt-3 flex flex-wrap items-center gap-2"><StatusBadge status={aggregate.status} /><CostStateBadge state={aggregate.costState} />{aggregate.mixedProgress && <Badge variant="gold">Mixed progress</Badge>}</div></div></div><div className="grid gap-4 p-5 sm:grid-cols-2 lg:grid-cols-4"><DetailValue label="Total quantity" value={`${aggregate.totalQuantity} pcs`} /><DetailValue label="Total BDT" value={<Money value={aggregate.totalBdt} currency="BDT" />} /><DetailValue label="Estimated weight" value={aggregate.totalWeightKg === null ? "Unavailable" : `${aggregate.totalWeightKg} kg`} /><DetailValue label="Product cost" value={<Money value={aggregate.productAmountCny} currency="CNY" />} /><DetailValue label="China warehouse" value={<Money value={aggregate.localDeliveryCny} currency="CNY" />} /><DetailValue label="To Guangzhou" value={<Money value={aggregate.guangzhouCostCny} currency="CNY" />} /><DetailValue label="Service charge" value={<Money value={aggregate.serviceChargeCny} currency="CNY" />} /><DetailValue label="Bangladesh shipping" value={<Money value={aggregate.bangladeshShippingBdt} currency="BDT" />} /></div>{aggregate.note && <p className="mx-5 mb-5 rounded-control bg-surface-muted p-3 text-sm text-muted">{aggregate.note}</p>}</Card><section><div className="mb-3 flex items-end justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[0.12em] text-action-primary">Submissions</p><h2 className="mt-1 text-xl font-semibold">Order submissions</h2></div><p className="text-sm text-muted">{detail.submissions.length} recorded</p></div><div className="space-y-4">{detail.submissions.map((submission) => <SubmissionCard key={submission.productOrderId} submission={submission} />)}</div></section></div>;
}

function SubmissionCard({ submission }: { submission: Submission }) { const [open, setOpen] = useState(false); return <Card data-ui="product-statement-submission" className="overflow-hidden shadow-soft"><button type="button" onClick={() => setOpen((value) => !value)} className="focus-ring flex w-full items-start justify-between gap-4 p-4 text-left sm:p-5"><div className="min-w-0"><p className="font-mono text-sm font-semibold text-action-primary">{submission.orderNumber}</p><p className="mt-1 text-sm text-muted">{new Intl.DateTimeFormat("en-BD", { dateStyle: "medium", timeStyle: "short" }).format(new Date(submission.submittedAt))} · {submission.totalQuantity} pcs</p><div className="mt-3 flex flex-wrap gap-2"><StatusBadge status={submission.status} /><CostStateBadge state={submission.costState} /></div></div><span className="mt-1 shrink-0 rounded-control border border-border p-2 text-muted">{open ? <ChevronUp className="h-4 w-4" /> : <ChevronDown className="h-4 w-4" />}</span></button>{open && <div className="border-t border-border p-4 sm:p-5"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><DetailValue label="Product cost" value={<Money value={submission.productAmountCny} currency="CNY" />} /><DetailValue label="Weight" value={submission.totalWeightKg === null ? "Unavailable" : `${submission.totalWeightKg} kg`} /><DetailValue label="Bangladesh shipping" value={<Money value={submission.bangladeshShippingBdt} currency="BDT" />} /><DetailValue label="Total BDT" value={<Money value={submission.totalBdt} currency="BDT" />} /></div><div className="mt-5 space-y-3">{submission.skuLines.map((line) => <div key={line.orderItemId} className="rounded-card border border-border p-3 text-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-semibold">{line.skuLabel}</p><p className="mt-1 text-xs text-muted">{Object.entries(line.attributes).map(([key, value]) => `${key}: ${value}`).join(" · ") || "Supplier SKU"}</p></div><div className="flex gap-2"><StatusBadge status={line.status} /><CostStateBadge state={line.costState} /></div></div><div className="mt-3 grid grid-cols-2 gap-3 border-t border-border pt-3"><DetailValue label="Quantity" value={`${line.quantity} pcs`} /><DetailValue label="Total" value={<Money value={line.totalBdt} currency="BDT" />} /><DetailValue label="Saved rate" value={line.exchangeRate === null ? "Unavailable" : `1 CNY = ${line.exchangeRate} BDT`} /><DetailValue label="Weight" value={line.weightKg === null ? "Unavailable" : `${line.weightKg} kg`} /></div>{line.note && <p className="mt-3 text-xs text-muted">{line.note}</p>}</div>)}</div></div>}</Card>; }
function DetailValue({ label, value }: { label: string; value: React.ReactNode }) { return <div className="min-w-0"><p className="text-xs font-bold uppercase tracking-[0.08em] text-muted">{label}</p><div className="mt-1 break-words font-semibold">{value}</div></div>; }
function Money({ value, currency }: { value: number | null; currency: "CNY" | "BDT" }) { return value === null ? "Unavailable" : <PriceDisplay value={value} currency={currency} showCode size="sm" />; }
function CostStateBadge({ state }: { state: CostState }) { const map = { actual: ["Actual", "success"], estimated: ["Estimated", "warning"], partial: ["Partial", "gold"], unavailable: ["Unavailable", "neutral"] } as const; const [label, variant] = map[state]; return <Badge variant={variant}>{label}</Badge>; }
