import { ArrowLeftRight, ArrowRight, Bell, Bookmark, CircleAlert, CircleDollarSign, ClipboardList, CreditCard, Landmark, Package, PackageCheck, ShieldCheck, Ship, ShoppingCart, Truck, WalletCards, Warehouse } from "lucide-react";
import Link from "next/link";
import { DashboardRefreshButton } from "@/components/client/dashboard-refresh-button";
import { Card, EmptyState, ErrorState, PriceDisplay, ProductThumbnail, Skeleton, StatusBadge } from "@/components/ui";
import { buttonClasses } from "@/components/ui/button";
import type { ClientDashboardSummary, DashboardOrder, DashboardStage } from "@/services/client-dashboard-service";

export function ClientDashboard({ name, summary }: { name: string; summary: ClientDashboardSummary }) {
  const attention = [
    summary.orders.uncoveredCny > 0 ? { id: "uncovered", icon: CircleDollarSign, title: "Wallet funding still required", detail: `CNY ${summary.orders.uncoveredCny.toFixed(2)} is not covered by active order reservations.`, href: "/client/wallet", tone: "text-danger" } : null,
    summary.orders.exceptionCount > 0 ? { id: "exception", icon: CircleAlert, title: `${summary.orders.exceptionCount} order${summary.orders.exceptionCount === 1 ? "" : "s"} need attention`, detail: "Review the current order status and any available notes.", href: "/client/orders", tone: "text-danger" } : null,
    summary.paymentsAwaitingReview > 0 ? { id: "proof", icon: CreditCard, title: `${summary.paymentsAwaitingReview} payment proof${summary.paymentsAwaitingReview === 1 ? "" : "s"} awaiting review`, detail: "Wallet credit is added only after admin verification.", href: "/client/wallet", tone: "text-warning" } : null,
    summary.notifications.unread > 0 ? { id: "notification", icon: Bell, title: `${summary.notifications.unread} unread update${summary.notifications.unread === 1 ? "" : "s"}`, detail: "Review notifications addressed to your account.", href: "/client/notifications", tone: "text-accent-violet" } : null,
  ].filter((item): item is NonNullable<typeof item> => item !== null);

  return <div data-page="client-dashboard" className="min-w-0 max-w-full space-y-6 sm:space-y-8">
    <header className="flex items-start justify-between gap-4"><div className="min-w-0"><h1 className="text-[2rem] font-bold leading-10 tracking-tight text-foreground">Good morning, {name}</h1><p className="mt-1 text-base text-muted">Here is your business overview.</p></div><div className="flex shrink-0 items-center gap-2"><Link href="/client/notifications" className="focus-ring relative grid h-11 w-11 place-items-center rounded-control text-foreground hover:bg-surface-muted lg:hidden" aria-label={`Open notifications, ${summary.notifications.unread} unread`}><Bell aria-hidden="true" className="h-6 w-6" />{summary.notifications.unread > 0 && <span aria-hidden="true" className="absolute right-0 top-0 min-w-5 rounded-full bg-action-primary px-1 text-center text-[0.65rem] font-bold leading-5 text-on-action">{summary.notifications.unread > 99 ? "99+" : summary.notifications.unread}</span>}</Link><DashboardRefreshButton /></div></header>
    <WalletOverview summary={summary} />
    <BalanceAllocation summary={summary} />
    <section className="grid gap-4 lg:grid-cols-[1.1fr_0.9fr]"><OrderProgress summary={summary} /><AttentionList items={attention} /></section>
    <section className="grid gap-6 xl:grid-cols-2"><RecentOrders orders={summary.orders.recent} /><RecentWalletActivity summary={summary} /></section>
    <RecentNotifications summary={summary} />
  </div>;
}

export function ClientDashboardSkeleton() {
  return <div aria-label="Loading business dashboard" role="status" className="space-y-6 sm:space-y-8"><div className="space-y-3"><Skeleton className="h-3 w-28" /><Skeleton className="h-9 w-64 sm:w-80" /><Skeleton className="h-5 w-56 sm:w-80" /></div><Skeleton className="h-[21rem] rounded-card sm:h-64" /><div className="grid gap-4 lg:grid-cols-2"><Skeleton className="h-64 rounded-card" /><Skeleton className="h-64 rounded-card" /></div><div className="grid gap-6 xl:grid-cols-2"><Skeleton className="h-72 rounded-card" /><Skeleton className="h-72 rounded-card" /></div></div>;
}

export function ClientDashboardError() { return <ErrorState title="Dashboard unavailable" description="Your current business overview could not be loaded. Refresh the dashboard or try again later." action={<DashboardRefreshButton />} />; }

function WalletOverview({ summary }: { summary: ClientDashboardSummary }) {
  const proofLabel = summary.paymentsAwaitingReview > 0 ? `${summary.paymentsAwaitingReview} payment proof${summary.paymentsAwaitingReview === 1 ? "" : "s"} under review` : "No payment proof awaiting review";
  return <Card className="min-w-0 max-w-full overflow-hidden border-action-primary/15 p-4 shadow-panel sm:p-6"><div className="flex min-w-0 flex-col gap-2.5 sm:gap-5"><div><p className="text-sm font-semibold text-muted">Available balance</p><PriceDisplay value={summary.wallet.availableBalanceCny} currency="CNY" showCode size="xl" className="mt-1 text-[2.25rem] sm:text-[2.5rem]" /></div><div className="grid grid-cols-[minmax(0,1fr)_minmax(0,1.1fr)] gap-2 border-t border-border pt-2.5 sm:grid-cols-2 sm:gap-4 sm:pt-4"><Metric icon={Bookmark} label="Active reservations" value={<PriceDisplay value={summary.wallet.activeReservedCny} currency="CNY" showCode />} detail="Held for active orders" /><Metric icon={ArrowLeftRight} label="Current rate" value={<span className="font-semibold tabular-nums text-foreground">1 CNY = {formatRate(summary.wallet.rateCnyToBdt)} BDT</span>} detail="Approved deposits retain their recorded rate" /></div><Link href="/client/wallet" className="focus-ring flex min-h-touch min-w-0 items-center gap-2.5 rounded-control border border-border bg-surface-muted px-3 py-1 hover:bg-action-soft sm:gap-3 sm:py-3"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-action-soft text-action-primary sm:h-10 sm:w-10"><ShieldCheck aria-hidden="true" className="h-4 w-4 sm:h-5 sm:w-5" /></span><span className="min-w-0 flex-1 break-words text-sm font-semibold text-foreground">{proofLabel}</span><ArrowRight aria-hidden="true" className="h-4 w-4 shrink-0 text-muted" /></Link><Link href="/client/wallet" className={buttonClasses({ variant: "primary", size: "lg", className: "w-full" })}><WalletCards aria-hidden="true" className="h-5 w-5" />Add funds</Link></div></Card>;
}

function BalanceAllocation({ summary }: { summary: ClientDashboardSummary }) {
  const total = summary.wallet.availableBalanceCny + summary.wallet.activeReservedCny;
  const availablePercent = total > 0 ? Math.round((summary.wallet.availableBalanceCny / total) * 100) : 0;
  return <Card className="relative min-w-0 max-w-full p-4 sm:p-6"><Link href="/client/wallet" aria-label="Open wallet allocation" className="focus-ring absolute right-3 top-3 grid h-11 w-11 place-items-center rounded-control text-muted hover:bg-surface-muted"><ArrowRight aria-hidden="true" className="h-5 w-5" /></Link><div className="grid min-w-0 gap-4 min-[390px]:grid-cols-[7rem_6rem_minmax(0,1fr)] min-[390px]:items-center min-[390px]:gap-2 sm:grid-cols-[minmax(10rem,1fr)_8rem_minmax(10rem,1fr)] sm:gap-6"><div className="min-w-0 pr-8 min-[390px]:pr-0"><h2 className="text-xl font-semibold tracking-tight min-[390px]:text-lg min-[390px]:leading-6 sm:text-xl sm:leading-7">Available vs reserved</h2><p className="mt-1 text-sm text-muted">Current wallet allocation</p></div><div className="relative mx-auto grid h-28 w-28 shrink-0 place-items-center rounded-full min-[390px]:h-24 min-[390px]:w-24 sm:h-32 sm:w-32" style={{ background: `conic-gradient(rgb(var(--color-accent-aqua)) 0 ${availablePercent}%, rgb(var(--color-accent-mint)) ${availablePercent}% 100%)` }}><div className="grid h-[4.5rem] w-[4.5rem] place-items-center rounded-full bg-surface text-center min-[390px]:h-16 min-[390px]:w-16 sm:h-20 sm:w-20"><span className="text-base font-bold tabular-nums text-foreground sm:text-lg">{new Intl.NumberFormat("en-BD", { maximumFractionDigits: 2 }).format(total)}</span><span className="text-[0.65rem] font-semibold text-muted sm:text-xs">CNY</span></div></div><div className="min-w-0 space-y-2.5"><AllocationItem color="bg-accent-aqua" label="Available" value={summary.wallet.availableBalanceCny} total={total} /><AllocationItem color="bg-accent-mint" label="Reserved" value={summary.wallet.activeReservedCny} total={total} /></div></div></Card>;
}

function AllocationItem({ color, label, value, total }: { color: string; label: string; value: number; total: number }) { const percentage = total > 0 ? ((value / total) * 100).toFixed(1) : "0.0"; return <div className="border-b border-border pb-3 last:border-0 last:pb-0"><p className="flex items-center gap-2 text-sm text-muted"><span className={`h-3 w-3 rounded-full ${color}`} />{label}</p><PriceDisplay value={value} currency="CNY" showCode size="sm" className="mt-1" /><p className="mt-0.5 text-xs text-muted">{percentage}%</p></div>; }

function OrderProgress({ summary }: { summary: ClientDashboardSummary }) {
  const stages: Array<{ stage: DashboardStage; label: string; icon: typeof ShoppingCart }> = [{ stage: "purchasing", label: "Purchase", icon: ShoppingCart }, { stage: "chinaWarehouse", label: "China warehouse", icon: Warehouse }, { stage: "guangzhou", label: "Guangzhou", icon: Truck }, { stage: "bangladesh", label: "Bangladesh", icon: Ship }, { stage: "readyForPickup", label: "Pickup", icon: Package }];
  return <Card className="min-w-0 max-w-full p-5 sm:p-6"><div className="flex min-w-0 flex-wrap items-center justify-between gap-3"><div className="min-w-0"><h2 className="text-xl font-semibold tracking-tight">Active shipments</h2><p className="mt-1 text-sm text-muted">{summary.orders.activeCount} open product order{summary.orders.activeCount === 1 ? "" : "s"}</p></div><Link href="/client/orders" className={buttonClasses({ variant: "ghost", size: "sm" })}>View all <ArrowRight aria-hidden="true" className="h-4 w-4" /></Link></div><div className="mt-6 grid min-w-0 grid-cols-5 gap-1">{stages.map(({ stage, label, icon: Icon }, index) => <div key={stage} className="relative min-w-0 text-center">{index > 0 && <span aria-hidden="true" className="absolute left-[-50%] right-[50%] top-5 h-px bg-border" />}<span className="relative mx-auto grid h-10 w-10 place-items-center rounded-full border border-border bg-surface text-action-primary"><Icon aria-hidden="true" className="h-5 w-5" /></span><p className="mt-2 text-sm font-bold tabular-nums text-foreground">{summary.orders.stages[stage]}</p><p className="mt-0.5 text-[0.62rem] font-semibold leading-4 text-muted">{label}</p></div>)}</div>{summary.orders.recent.length > 0 && <div className="mt-6 divide-y divide-border rounded-card border border-border">{summary.orders.recent.slice(0, 2).map((order) => <Link href="/client/orders" key={order.orderId} className="focus-ring flex min-w-0 items-center gap-3 px-3 py-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-control bg-surface-muted text-action-primary"><Package aria-hidden="true" className="h-5 w-5" /></span><span className="min-w-0 flex-1 break-all"><span className="block text-sm font-semibold text-foreground">{order.displayOrderNumber}</span><span className="block text-xs text-muted">{formatDate(order.orderedAt)}</span></span><StatusBadge status={order.status} /><ArrowRight aria-hidden="true" className="h-4 w-4 shrink-0 text-muted" /></Link>)}</div>}</Card>;
}

type AttentionItem = { id: string; icon: typeof Bell; title: string; detail: string; href: string; tone: string };
function AttentionList({ items }: { items: AttentionItem[] }) {
  if (!items.length) return <EmptyState title="No actions need your attention" description="Current wallet, order, payment, and notification signals are clear." icon={<PackageCheck aria-hidden="true" className="h-5 w-5 text-success" />} />;
  return <Card className="p-5 sm:p-6"><div className="flex items-center justify-between gap-3"><div><h2 className="text-xl font-semibold tracking-tight">Needs attention</h2><p className="mt-1 text-sm text-muted">Items supported by your current account data.</p></div><CircleAlert aria-hidden="true" className="h-5 w-5 text-warning" /></div><div className="mt-4 divide-y divide-border">{items.map(({ id, icon: Icon, title, detail, href, tone }) => <Link key={id} href={href} className="focus-ring flex min-h-touch items-start gap-3 py-3 first:pt-0 last:pb-0"><span className={`grid h-10 w-10 shrink-0 place-items-center rounded-control bg-surface-muted ${tone}`}><Icon aria-hidden="true" className="h-5 w-5" /></span><span className="min-w-0 flex-1"><span className="block text-sm font-semibold text-foreground">{title}</span><span className="mt-1 block text-sm leading-5 text-muted">{detail}</span></span><ArrowRight aria-hidden="true" className="mt-2 h-4 w-4 shrink-0 text-muted" /></Link>)}</div></Card>;
}

function RecentOrders({ orders }: { orders: DashboardOrder[] }) {
  if (!orders.length) return <EmptyState title="No confirmed orders yet" description="Confirm a product selection to see its real status and saved cost here." icon={<ClipboardList aria-hidden="true" className="h-5 w-5" />} action={<Link href="/client/order/new" className={buttonClasses({ variant: "primary", size: "md" })}>Start a new order <ArrowRight aria-hidden="true" className="h-4 w-4" /></Link>} />;
  return <Card className="min-w-0 max-w-full p-5 sm:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div className="min-w-0"><h2 className="text-xl font-semibold tracking-tight">Recent orders</h2><p className="mt-1 text-sm text-muted">Latest product orders and their current status.</p></div><Link href="/client/orders" className={buttonClasses({ variant: "ghost", size: "sm" })}>View all <ArrowRight aria-hidden="true" className="h-4 w-4" /></Link></div><div className="mt-4 divide-y divide-border">{orders.map((order) => <Link href="/client/orders" key={order.orderId} className="focus-ring flex min-w-0 items-start gap-3 py-4 first:pt-0 last:pb-0"><ProductThumbnail src={order.productImageUrl} alt={order.productTitle} size="md" /><div className="min-w-0 flex-1"><p className="text-sm font-semibold text-foreground">{order.quantity} {order.quantity === 1 ? "item" : "items"}</p><p className="mt-1 text-xs text-muted">Ordered {formatDate(order.orderedAt)}</p><div className="mt-2 flex flex-wrap items-center justify-between gap-2"><StatusBadge status={order.status} className="max-w-full whitespace-normal text-center" />{order.totalAmountCny !== null && <PriceDisplay value={order.totalAmountCny} currency="CNY" showCode size="sm" />}</div></div></Link>)}</div></Card>;
}

function RecentWalletActivity({ summary }: { summary: ClientDashboardSummary }) {
  if (!summary.wallet.recentTransactions.length) return <EmptyState title="No wallet activity yet" description="Approved credits, reservations, and order debits will appear after they are recorded." icon={<Landmark aria-hidden="true" className="h-5 w-5" />} action={<Link href="/client/wallet" className={buttonClasses({ variant: "outline", size: "md" })}>Open wallet <ArrowRight aria-hidden="true" className="h-4 w-4" /></Link>} />;
  return <Card className="p-5 sm:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-semibold tracking-tight">Recent wallet activity</h2><p className="mt-1 text-sm text-muted">Your latest ledger entries.</p></div><Link href="/client/wallet" className={buttonClasses({ variant: "ghost", size: "sm" })}>Open wallet <ArrowRight aria-hidden="true" className="h-4 w-4" /></Link></div><div className="mt-4 divide-y divide-border">{summary.wallet.recentTransactions.map((transaction) => <Link href="/client/wallet" key={transaction.id} className="focus-ring flex items-start justify-between gap-4 py-4 first:pt-0 last:pb-0"><div className="min-w-0"><p className="text-sm font-semibold text-foreground">{humanize(transaction.type)}</p><p className="mt-1 text-xs text-muted">{formatDate(transaction.createdAt)}</p></div><PriceDisplay value={transaction.amountCny} currency="CNY" showCode size="sm" className={transaction.amountCny < 0 ? "text-danger" : "text-success"} /></Link>)}</div></Card>;
}

function RecentNotifications({ summary }: { summary: ClientDashboardSummary }) {
  if (!summary.notifications.recent.length) return null;
  return <Card className="p-5 sm:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-semibold tracking-tight">Recent updates</h2><p className="mt-1 text-sm text-muted">Notifications addressed to your account.</p></div><Link href="/client/notifications" className={buttonClasses({ variant: "ghost", size: "sm" })}>All notifications <ArrowRight aria-hidden="true" className="h-4 w-4" /></Link></div><div className="mt-4 divide-y divide-border">{summary.notifications.recent.map((notification) => <Link key={notification.id} href="/client/notifications" className="focus-ring block py-4 first:pt-0 last:pb-0"><div className="flex items-start gap-3"><span className={`mt-0.5 grid h-9 w-9 shrink-0 place-items-center rounded-control ${notification.readAt ? "bg-surface-muted text-muted" : "bg-action-soft text-action-primary"}`}><Bell aria-hidden="true" className="h-4 w-4" /></span><span className="min-w-0 flex-1"><span className="block text-sm font-semibold text-foreground">{notification.title}</span><span className="mt-1 block text-sm leading-5 text-muted">{notification.body}</span><span className="mt-1 block text-xs text-muted">{formatDate(notification.createdAt)}</span></span></div></Link>)}</div></Card>;
}

function Metric({ icon: Icon, label, value, detail }: { icon: typeof Landmark; label: string; value: React.ReactNode; detail: string }) { return <div className="flex min-w-0 items-start gap-2 sm:gap-3"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-action-soft text-action-primary sm:h-10 sm:w-10"><Icon aria-hidden="true" className="h-4 w-4 sm:h-5 sm:w-5" /></span><div className="min-w-0"><p className="text-xs font-semibold leading-4 text-muted">{label}</p><div className="mt-0.5 text-sm">{value}</div><p className="mt-1 hidden text-xs leading-5 text-muted sm:block">{detail}</p></div></div>; }
function formatRate(value: number) { return new Intl.NumberFormat("en-BD", { minimumFractionDigits: 2, maximumFractionDigits: 4 }).format(value); }
function formatDate(value: string) { return new Intl.DateTimeFormat("en-BD", { dateStyle: "medium" }).format(new Date(value)); }
function humanize(value: string) { return value.replaceAll("_", " ").replace(/\b\w/g, (character) => character.toUpperCase()); }
