"use client";

import { BarChart3, ChevronLeft, ChevronRight, RefreshCw } from "lucide-react";
import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Alert, Badge, Button, Card, EmptyState, Input, LoadingState, PageHeader, PriceDisplay, ProductThumbnail, Select, StatusBadge } from "@/components/ui";
import { buttonClasses } from "@/components/ui/button";
import type { OrderStatus } from "@/lib/domain/types";

type CostState = "actual" | "estimated" | "partial" | "unavailable";
type StatementRow = { product_link_id: string; product_code: string | null; product_title: string | null; product_images: string[] | null; category: string; total_quantity: number | string; product_amount_cny: number | string | null; local_delivery_cny: number | string | null; total_weight_kg: number | string | null; guangzhou_cost_cny: number | string | null; bangladesh_shipping_bdt: number | string | null; service_charge_cny: number | string | null; total_bdt: number | string | null; average_unit_cost_bdt: number | string | null; status: OrderStatus; mixed_progress: boolean; cost_state: CostState; note: string | null };
type ChartCategory = { category: string; ordered_products: number; total_quantity: number; total_weight_kg: number | null };
type Chart = { orderedProducts: number; totalQuantity: number; totalWeightKg: number | null; totalBdt: number | null; categories: ChartCategory[] };
export type StatementResponse = { data: StatementRow[]; meta: { page: number; pageSize: number; total: number; chart: Chart } };
type Filters = { startDate: string; endDate: string; month: string; category: string; status: string };
const initialFilters: Filters = { startDate: "", endDate: "", month: "", category: "", status: "" };

export function ClientProductStatement({ fixtureData }: { fixtureData?: StatementResponse } = {}) {
  const [filters, setFilters] = useState<Filters>(initialFilters);
  const [appliedFilters, setAppliedFilters] = useState<Filters>(initialFilters);
  const [page, setPage] = useState(1);
  const [statement, setStatement] = useState<StatementResponse | undefined>(fixtureData);
  const [loading, setLoading] = useState(!fixtureData);
  const [error, setError] = useState<string>();
  const load = useCallback(async (signal?: AbortSignal) => {
    if (fixtureData) { setStatement(fixtureData); setLoading(false); return; }
    setLoading(true); setError(undefined);
    const query = new URLSearchParams({ page: String(page) });
    (Object.entries(appliedFilters) as Array<[keyof Filters, string]>).forEach(([key, value]) => { if (value) query.set(key, value); });
    try {
      const response = await fetch(`/api/client/product-statement?${query.toString()}`, { signal, cache: "no-store" });
      const payload = await response.json().catch(() => ({})) as StatementResponse & { error?: { message?: string } };
      if (!response.ok || !Array.isArray(payload.data) || !payload.meta?.chart) throw new Error(payload.error?.message || "We could not load your product details.");
      setStatement(payload);
    } catch (cause) {
      if ((cause as Error).name !== "AbortError") setError(cause instanceof Error ? cause.message : "We could not load your product details.");
    } finally { if (!signal?.aborted) setLoading(false); }
  }, [appliedFilters, fixtureData, page]);
  useEffect(() => { const controller = new AbortController(); void load(controller.signal); return () => controller.abort(); }, [load]);
  function applyFilters(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setPage(1); setAppliedFilters(filters); }
  function clearFilters() { setFilters(initialFilters); setAppliedFilters(initialFilters); setPage(1); }
  const categoryOptions = statement?.meta.chart.categories.map((entry) => entry.category).filter((value) => value !== "mixed") ?? [];
  const totalPages = Math.max(1, Math.ceil((statement?.meta.total ?? 0) / 30));
  return <><PageHeader eyebrow="Product statement" title="Product statement" description="One row per product link. Colors and sizes are combined while costs and shipping progress remain traceable." />
    <StatementChart chart={statement?.meta.chart} loading={loading && !statement} />
    <Card className="mt-6 p-4 shadow-soft sm:p-5"><form onSubmit={applyFilters} className="grid gap-3 md:grid-cols-2 xl:grid-cols-5" aria-label="Filter product details">
      <Input label="From date" type="date" value={filters.startDate} onChange={(event) => setFilters((value) => ({ ...value, startDate: event.target.value }))} />
      <Input label="To date" type="date" value={filters.endDate} onChange={(event) => setFilters((value) => ({ ...value, endDate: event.target.value }))} />
      <Input label="Month" type="month" value={filters.month} onChange={(event) => setFilters((value) => ({ ...value, month: event.target.value }))} />
      <div><Input label="Category" list="statement-categories" value={filters.category} onChange={(event) => setFilters((value) => ({ ...value, category: event.target.value }))} placeholder="All categories" /><datalist id="statement-categories">{categoryOptions.map((category) => <option key={category} value={category} />)}</datalist></div>
      <Select label="Status" value={filters.status} onChange={(event) => setFilters((value) => ({ ...value, status: event.target.value }))}><option value="">All statuses</option>{statusOptions.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</Select>
      <div className="flex items-end gap-2 md:col-span-2 xl:col-span-5"><Button type="submit" loading={loading} className="min-w-28">Apply filters</Button><button type="button" onClick={clearFilters} className={buttonClasses({ variant: "ghost", size: "md" })}>Clear</button></div>
    </form></Card>
    <section className="mt-6" aria-live="polite">{error ? <ErrorPanel message={error} retry={() => void load()} /> : loading && !statement ? <LoadingState label="Loading product details" /> : statement?.data.length === 0 ? <EmptyState title="No product details found" description="Try changing the date, category, or status filters." /> : statement ? <><StatementCards rows={statement.data} /><div className="hidden lg:block"><StatementTable rows={statement.data} /></div></> : null}</section>
    {statement && statement.meta.total > 0 && <Pagination page={page} totalPages={totalPages} onPageChange={setPage} />}</>;
}

const statusOptions: Array<[OrderStatus, string]> = [["pending_admin_review", "Under review"], ["confirmed", "Confirmed"], ["queued_for_purchase", "Purchasing"], ["purchased", "Purchased"], ["seller_shipped", "Supplier shipped"], ["received_china", "Received in China"], ["qc_checked", "Checked in China"], ["packed", "Packed"], ["sent_guangzhou", "Sent to Guangzhou"], ["arrived_guangzhou", "At Guangzhou hub"], ["sent_bangladesh", "On the way to Bangladesh"], ["arrived_bangladesh", "Arrived in Bangladesh"], ["ready_for_pickup", "Ready for pickup"], ["completed", "Completed"], ["cancelled", "Cancelled"], ["exception", "Needs attention"]];

function StatementChart({ chart, loading }: { chart?: Chart; loading: boolean }) { const maxQuantity = Math.max(1, ...(chart?.categories.map((entry) => Number(entry.total_quantity)) ?? [1])); return <section className="mt-7" aria-label="Filtered product summary"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Ordered products" value={chart?.orderedProducts} loading={loading} /><Metric label="Total quantity" value={chart?.totalQuantity} loading={loading} /><Metric label="Total weight" value={chart?.totalWeightKg === null || chart?.totalWeightKg === undefined ? "—" : `${formatNumber(chart.totalWeightKg, 3)} kg`} loading={loading} /><Metric label="Total BDT price" value={chart?.totalBdt === null || chart?.totalBdt === undefined ? "—" : formatCurrency(chart.totalBdt)} loading={loading} /></div><Card className="mt-3 p-4 shadow-soft sm:p-5"><div className="flex items-center gap-2"><BarChart3 aria-hidden="true" className="h-4 w-4 text-action-primary" /><h2 className="font-semibold">Category-wise ordered quantity</h2></div>{chart?.categories.length ? <div className="mt-4 space-y-3">{chart.categories.map((entry) => <div key={entry.category} className="grid grid-cols-[minmax(5rem,10rem)_1fr_auto] items-center gap-3 text-sm"><span className="truncate font-medium" title={entry.category}>{entry.category}</span><span className="h-2 overflow-hidden rounded-full bg-surface-muted"><span className="block h-full rounded-full bg-accent-mint" style={{ width: `${Math.max(4, (Number(entry.total_quantity) / maxQuantity) * 100)}%` }} /></span><span className="tabular-nums text-muted">{formatNumber(entry.total_quantity)}</span></div>)}</div> : <p className="mt-3 text-sm text-muted">{loading ? "Loading chart…" : "No category data for these filters."}</p>}</Card></section>; }
function Metric({ label, value, loading }: { label: string; value: string | number | undefined; loading: boolean }) { return <Card className="p-4 shadow-soft"><p className="text-xs font-bold uppercase tracking-[0.1em] text-muted">{label}</p><p className="mt-2 text-2xl font-bold tabular-nums">{loading && value === undefined ? "…" : value ?? "0"}</p></Card>; }
function StatementCards({ rows }: { rows: StatementRow[] }) { return <div data-ui="product-statement-cards" className="space-y-4 lg:hidden">{rows.map((row) => <StatementCard key={row.product_link_id} row={row} />)}</div>; }
function StatementCard({ row }: { row: StatementRow }) { return <Card data-ui="product-statement-card" className="overflow-hidden p-4 shadow-soft sm:p-5"><div className="flex items-start gap-3"><ProductImage images={row.product_images} /><div className="min-w-0 flex-1"><div className="flex flex-wrap items-start justify-between gap-2"><div className="min-w-0"><p className="text-xs font-bold uppercase tracking-[0.1em] text-muted">{row.category || "Uncategorized"}</p><h2 className="mt-1 break-words text-base font-semibold leading-6">{row.product_title || "Supplier product"}</h2></div><StatusBadge status={row.status} /></div><div className="mt-2 flex flex-wrap items-center gap-2"><p className="font-mono text-xs text-muted">{row.product_code || "Product code unavailable"}</p><CostStateBadge state={row.cost_state} /></div>{row.mixed_progress && <p className="mt-2 text-xs font-semibold text-warning">Mixed progress across submissions</p>}</div></div><div className="mt-4 grid grid-cols-2 gap-x-4 gap-y-4 border-y border-border py-4 text-sm"><StatementValue label="Total quantity" value={`${formatNumber(row.total_quantity)} pcs`} /><StatementValue label="Total BDT" value={<MoneyValue value={row.total_bdt} currency="BDT" />} /><StatementValue label="Product cost" value={<MoneyValue value={row.product_amount_cny} currency="CNY" />} /><StatementValue label="Estimated weight" value={row.total_weight_kg === null ? "Unavailable" : `${formatNumber(row.total_weight_kg, 3)} kg`} /><StatementValue label="Bangladesh shipping" value={<MoneyValue value={row.bangladesh_shipping_bdt} currency="BDT" />} /><StatementValue label="Average per unit" value={<MoneyValue value={row.average_unit_cost_bdt} currency="BDT" />} /></div>{row.note && <p className="mt-4 rounded-control bg-surface-muted px-3 py-2 text-sm leading-5 text-muted">{row.note}</p>}<Link href={`/client/excel-details/${row.product_link_id}`} className={buttonClasses({ variant: "outline", size: "sm", className: "mt-4 w-full" })}>View submission details</Link></Card>; }
function StatementValue({ label, value }: { label: string; value: React.ReactNode }) { return <div className="min-w-0"><p className="text-xs font-bold uppercase tracking-[0.08em] text-muted">{label}</p><div className="mt-1 break-words font-semibold text-foreground">{value}</div></div>; }
function MoneyValue({ value, currency }: { value: number | string | null; currency: "CNY" | "BDT" }) { return value === null ? "Unavailable" : <PriceDisplay value={value} currency={currency} showCode size="sm" />; }
function StatementTable({ rows }: { rows: StatementRow[] }) { return <div data-ui="product-statement-table" className="overflow-x-auto rounded-card border border-border bg-surface shadow-soft"><table className="min-w-[1550px] w-full text-left text-sm"><thead className="bg-surface-muted text-xs uppercase tracking-wide text-muted"><tr><th className="p-3">Product picture</th><th>Product amount</th><th>Local delivery</th><th>Weight</th><th>Quantity</th><th>To Guangzhou</th><th>BD shipping</th><th>Service (6%)</th><th>Total</th><th>Avg. unit</th><th>Status</th><th className="p-3">Note</th></tr></thead><tbody className="divide-y divide-border">{rows.map((row) => <tr key={row.product_link_id} className="align-top"><td className="p-3"><div className="flex min-w-24 flex-col gap-2"><ProductImage images={row.product_images} /><p className="text-xs text-muted">Code: {row.product_code || "—"}</p><CostStateBadge state={row.cost_state} /></div></td><MoneyCell value={row.product_amount_cny} currency="CNY" /><MoneyCell value={row.local_delivery_cny} currency="CNY" /><td>{row.total_weight_kg === null ? "—" : `${formatNumber(row.total_weight_kg, 3)} kg`}</td><td className="tabular-nums">{formatNumber(row.total_quantity)}</td><MoneyCell value={row.guangzhou_cost_cny} currency="CNY" /><MoneyCell value={row.bangladesh_shipping_bdt} currency="BDT" /><MoneyCell value={row.service_charge_cny} currency="CNY" /><MoneyCell value={row.total_bdt} currency="BDT" /><MoneyCell value={row.average_unit_cost_bdt} currency="BDT" /><td><StatusBadge status={row.status} />{row.mixed_progress && <p className="mt-1 text-xs font-medium text-warning">Mixed progress</p>}</td><td className="max-w-64 whitespace-normal p-3 text-muted">{row.note || "—"}</td></tr>)}</tbody></table></div>; }
function ProductImage({ images }: { images: string[] | null }) { return <ProductThumbnail src={images?.[0]} alt="Product" size="lg" />; }
function MoneyCell({ value, currency }: { value: number | string | null; currency: "CNY" | "BDT" }) { return <td className="whitespace-nowrap">{value === null ? "—" : <PriceDisplay value={value} currency={currency} showCode size="sm" />}</td>; }
function CostStateBadge({ state }: { state: CostState }) { const presentation = { actual: ["Actual", "success"], estimated: ["Estimated", "warning"], partial: ["Partial", "gold"], unavailable: ["Not available", "neutral"] } as const; const [label, variant] = presentation[state]; return <Badge variant={variant} className="mt-2">{label}</Badge>; }
function ErrorPanel({ message, retry }: { message: string; retry: () => void }) { return <Card className="p-5 shadow-panel"><Alert variant="danger" title="Product details unavailable">{message}<Button type="button" variant="outline" size="sm" onClick={retry} className="mt-3"><RefreshCw aria-hidden="true" className="h-4 w-4" />Try again</Button></Alert></Card>; }
function Pagination({ page, totalPages, onPageChange }: { page: number; totalPages: number; onPageChange: (page: number) => void }) { const pages = useMemo(() => pageNumbers(page, totalPages), [page, totalPages]); return <nav className="mt-6 flex flex-wrap items-center justify-center gap-1" aria-label="Product details pages"><button type="button" disabled={page === 1} onClick={() => onPageChange(page - 1)} className={buttonClasses({ variant: "outline", size: "sm" })}><ChevronLeft aria-hidden="true" className="h-4 w-4" />Previous</button>{pages.map((value, index) => value === null ? <span key={`gap-${index}`} className="px-2 text-muted">…</span> : <button key={value} type="button" onClick={() => onPageChange(value)} aria-current={value === page ? "page" : undefined} className={buttonClasses({ variant: value === page ? "primary" : "outline", size: "sm" })}>{value}</button>)}<button type="button" disabled={page === totalPages} onClick={() => onPageChange(page + 1)} className={buttonClasses({ variant: "outline", size: "sm" })}>Next<ChevronRight aria-hidden="true" className="h-4 w-4" /></button></nav>; }
function pageNumbers(page: number, total: number): Array<number | null> { if (total <= 7) return Array.from({ length: total }, (_, index) => index + 1); const middle = [page - 1, page, page + 1].filter((value) => value > 1 && value < total); return [1, ...(middle[0] > 2 ? [null] : []), ...middle, ...(middle.at(-1)! < total - 1 ? [null] : []), total]; }
function formatNumber(value: number | string, maximumFractionDigits = 0) { const number = Number(value); return Number.isFinite(number) ? new Intl.NumberFormat("en-BD", { maximumFractionDigits }).format(number) : "—"; }
function formatCurrency(value: number | string) { const number = Number(value); return Number.isFinite(number) ? new Intl.NumberFormat("en-BD", { style: "currency", currency: "BDT", currencyDisplay: "narrowSymbol", maximumFractionDigits: 2 }).format(number) : "—"; }
