export type ShippingTariffItem = {
  group: string;
  item: string;
  rateBdtPerKg: number;
};

export const SHIPPING_TARIFFS: readonly ShippingTariffItem[] = [
  { group: "Bag Items", item: "Wallet", rateBdtPerKg: 750 },
  { group: "Bag Items", item: "Vanity Bag", rateBdtPerKg: 750 },
  { group: "Bag Items", item: "Back Pack", rateBdtPerKg: 750 },
  { group: "Bag Items", item: "Cross Body", rateBdtPerKg: 750 },
  { group: "Bag Items", item: "School Bag", rateBdtPerKg: 750 },
  { group: "Bag Items", item: "Mini Bag", rateBdtPerKg: 750 },
  { group: "Bag Items", item: "Ladies/Hand Purse", rateBdtPerKg: 750 },
  { group: "Bag Items", item: "Storage Bag", rateBdtPerKg: 750 },
  { group: "Shoes And Slipper", item: "Sandle", rateBdtPerKg: 760 },
  { group: "Shoes And Slipper", item: "Soles and Insoles", rateBdtPerKg: 750 },
  { group: "Shoes And Slipper", item: "Ladies Slipper", rateBdtPerKg: 760 },
  { group: "Shoes And Slipper", item: "Ladies Shoe", rateBdtPerKg: 750 },
  { group: "Shoes And Slipper", item: "Mens Keds", rateBdtPerKg: 750 },
  { group: "Shoes And Slipper", item: "Nagra", rateBdtPerKg: 750 },
  { group: "Shoes And Slipper", item: "Mens Shoe/Boots", rateBdtPerKg: 750 },
  { group: "Shoes And Slipper", item: "Baby Footwear", rateBdtPerKg: 780 },
  { group: "Shoes And Slipper", item: "Infant Shoe", rateBdtPerKg: 780 },
  { group: "Plastics, Kitchen Accessories, Home Decore, Households Accessories", item: "Carboys, Bottles, Flasks and Similar Articles of Plastics", rateBdtPerKg: 750 },
  { group: "Plastics, Kitchen Accessories, Home Decore, Households Accessories", item: "Stoppers, Lids, Caps and Other Closures of Plastics", rateBdtPerKg: 750 },
  { group: "Plastics, Kitchen Accessories, Home Decore, Households Accessories", item: "Articles for the Packing of goods, of plastics nes", rateBdtPerKg: 750 },
  { group: "Plastics, Kitchen Accessories, Home Decore, Households Accessories", item: "Table Matt (Plastic)", rateBdtPerKg: 750 },
  { group: "Plastics, Kitchen Accessories, Home Decore, Households Accessories", item: "Vaccum Cup", rateBdtPerKg: 750 },
  { group: "Plastics, Kitchen Accessories, Home Decore, Households Accessories", item: "Tissue Box of Plastic", rateBdtPerKg: 750 },
  { group: "Plastics, Kitchen Accessories, Home Decore, Households Accessories", item: "Storage Box", rateBdtPerKg: 750 },
  { group: "Plastics, Kitchen Accessories, Home Decore, Households Accessories", item: "Kitchen Knife", rateBdtPerKg: 800 },
  { group: "Plastics, Kitchen Accessories, Home Decore, Households Accessories", item: "Decoration Item Plastic", rateBdtPerKg: 750 },
  { group: "Plastics, Kitchen Accessories, Home Decore, Households Accessories", item: "Plastic Item", rateBdtPerKg: 750 },
  { group: "Plastics, Kitchen Accessories, Home Decore, Households Accessories", item: "Empty Bottle (Plastic)", rateBdtPerKg: 750 },
  { group: "Plastics, Kitchen Accessories, Home Decore, Households Accessories", item: "Home Decoration", rateBdtPerKg: 750 },
  { group: "Plastics, Kitchen Accessories, Home Decore, Households Accessories", item: "Paper Box", rateBdtPerKg: 750 },
  { group: "Plastics, Kitchen Accessories, Home Decore, Households Accessories", item: "Wet Tissue", rateBdtPerKg: 1000 },
  { group: "Plastics, Kitchen Accessories, Home Decore, Households Accessories", item: "Empty Box (Paper)", rateBdtPerKg: 750 },
  { group: "Plastics, Kitchen Accessories, Home Decore, Households Accessories", item: "Wall Sticker/Sticker Printed", rateBdtPerKg: 750 },
  { group: "Plastics, Kitchen Accessories, Home Decore, Households Accessories", item: "Dust Cloth", rateBdtPerKg: 750 },
  { group: "Plastics, Kitchen Accessories, Home Decore, Households Accessories", item: "Artificial Flower", rateBdtPerKg: 750 },
  { group: "Plastics, Kitchen Accessories, Home Decore, Households Accessories", item: "Mini Hand Juicer", rateBdtPerKg: 750 },
  { group: "Plastics, Kitchen Accessories, Home Decore, Households Accessories", item: "Mixer Blender 3 in 1", rateBdtPerKg: 750 },
  { group: "Plastics, Kitchen Accessories, Home Decore, Households Accessories", item: "Iron", rateBdtPerKg: 750 },
  { group: "Plastics, Kitchen Accessories, Home Decore, Households Accessories", item: "Hair Dryer", rateBdtPerKg: 780 },
  { group: "Plastics, Kitchen Accessories, Home Decore, Households Accessories", item: "Cutlery", rateBdtPerKg: 780 },
  { group: "Plastics, Kitchen Accessories, Home Decore, Households Accessories", item: "Hair Straightener", rateBdtPerKg: 780 },
  { group: "Plastics, Kitchen Accessories, Home Decore, Households Accessories", item: "Kettle", rateBdtPerKg: 750 },
  { group: "Plastics, Kitchen Accessories, Home Decore, Households Accessories", item: "Table Lamp without Battery", rateBdtPerKg: 750 },
  { group: "Plastics, Kitchen Accessories, Home Decore, Households Accessories", item: "Table Lamp & LED Light with Battery", rateBdtPerKg: 980 },
  { group: "Plastics, Kitchen Accessories, Home Decore, Households Accessories", item: "LED Light", rateBdtPerKg: 780 },
  { group: "Plastics, Kitchen Accessories, Home Decore, Households Accessories", item: "Strip Light", rateBdtPerKg: 780 },
  { group: "Ready Made Garments", item: "Carpet+MAT", rateBdtPerKg: 750 },
  { group: "Ready Made Garments", item: "Prayer Mate", rateBdtPerKg: 750 },
  { group: "Ready Made Garments", item: "Blazer", rateBdtPerKg: 1500 },
  { group: "Ready Made Garments", item: "Hoodie", rateBdtPerKg: 810 },
  { group: "Ready Made Garments", item: "Muffler", rateBdtPerKg: 800 },
  { group: "Ready Made Garments", item: "Jacket (Gents) (Ladies)", rateBdtPerKg: 820 },
  { group: "Ready Made Garments", item: "Ladies Winter Wear", rateBdtPerKg: 820 },
  { group: "Ready Made Garments", item: "Baby Sweater", rateBdtPerKg: 820 },
  { group: "Ready Made Garments", item: "Ladies Shawl", rateBdtPerKg: 850 },
  { group: "Ready Made Garments", item: "Blanket", rateBdtPerKg: 900 },
  { group: "Ready Made Garments", item: "Jeans Pant", rateBdtPerKg: 950 },
  { group: "Ready Made Garments", item: "Pant", rateBdtPerKg: 900 },
  { group: "Ready Made Garments", item: "Infant/Baby Pant", rateBdtPerKg: 920 },
  { group: "Ready Made Garments", item: "Undergarments", rateBdtPerKg: 850 },
  { group: "Ready Made Garments", item: "T-Shirt", rateBdtPerKg: 900 },
  { group: "Ready Made Garments", item: "Shirt", rateBdtPerKg: 880 },
  { group: "Ready Made Garments", item: "Baby T-Shirt", rateBdtPerKg: 950 },
  { group: "Ready Made Garments", item: "Jersey", rateBdtPerKg: 900 },
  { group: "Ready Made Garments", item: "Orna", rateBdtPerKg: 900 },
  { group: "Ready Made Garments", item: "Baby Jersey", rateBdtPerKg: 920 },
  { group: "Ready Made Garments", item: "Borka", rateBdtPerKg: 920 },
  { group: "Ready Made Garments", item: "Swimming Wear", rateBdtPerKg: 750 },
  { group: "Ready Made Garments", item: "Socks, Hats, Hand Gloves", rateBdtPerKg: 800 },
  { group: "Ready Made Garments", item: "Rain Coat", rateBdtPerKg: 800 },
  { group: "Ready Made Garments", item: "Trouser", rateBdtPerKg: 850 },
  { group: "Ready Made Garments", item: "Payjama", rateBdtPerKg: 850 },
  { group: "Ready Made Garments", item: "Leggings", rateBdtPerKg: 850 },
  { group: "Ready Made Garments", item: "Ladies Tops", rateBdtPerKg: 880 },
  { group: "Ready Made Garments", item: "Nighty", rateBdtPerKg: 820 },
  { group: "Ready Made Garments", item: "Ladies Tops Shirts", rateBdtPerKg: 850 },
  { group: "Ready Made Garments", item: "Cap", rateBdtPerKg: 780 },
  { group: "Ready Made Garments", item: "Kotti", rateBdtPerKg: 950 },
  { group: "Ready Made Garments", item: "Girls Frock", rateBdtPerKg: 840 },
  { group: "Ready Made Garments", item: "Baby Frock", rateBdtPerKg: 850 },
  { group: "Ready Made Garments", item: "Skirt", rateBdtPerKg: 840 },
  { group: "Ready Made Garments", item: "Hijab/Scarf", rateBdtPerKg: 880 },
  { group: "Ready Made Garments", item: "Baby Wear set", rateBdtPerKg: 870 },
  { group: "Ready Made Garments", item: "Towel", rateBdtPerKg: 800 },
  { group: "Ready Made Garments", item: "Pillow Cover", rateBdtPerKg: 800 },
  { group: "Ready Made Garments", item: "Table Matt (Fabric)", rateBdtPerKg: 800 },
  { group: "Ready Made Garments", item: "Curtain (Fabric)", rateBdtPerKg: 800 },
  { group: "Ready Made Garments", item: "Bed Sheet", rateBdtPerKg: 800 },
  { group: "Ready Made Garments", item: "Life Jacket", rateBdtPerKg: 750 },
  { group: "Machineries, Electronic, Car Accessories", item: "Conveyor or Transmission Belts of Belting", rateBdtPerKg: 700 },
  { group: "Machineries, Electronic, Car Accessories", item: "Rubber Belt Round Not Exceeding 10 in DIA Flat", rateBdtPerKg: 700 },
  { group: "Machineries, Electronic, Car Accessories", item: "Rubber Roller", rateBdtPerKg: 700 },
  { group: "Machineries, Electronic, Car Accessories", item: "Pump", rateBdtPerKg: 700 },
  { group: "Machineries, Electronic, Car Accessories", item: "Welding Machine", rateBdtPerKg: 750 },
  { group: "Machineries, Electronic, Car Accessories", item: "Compressor", rateBdtPerKg: 700 },
  { group: "Machineries, Electronic, Car Accessories", item: "Small Fan/Portable Fan (With Battery)", rateBdtPerKg: 950 },
  { group: "Machineries, Electronic, Car Accessories", item: "Small Fan/Portable Fan (Without Battery)", rateBdtPerKg: 750 },
  { group: "Machineries, Electronic, Car Accessories", item: "Oil Filter", rateBdtPerKg: 700 },
  { group: "Machineries, Electronic, Car Accessories", item: "Water Filter", rateBdtPerKg: 700 },
  { group: "Machineries, Electronic, Car Accessories", item: "Air Filter", rateBdtPerKg: 700 },
  { group: "Machineries, Electronic, Car Accessories", item: "Drill Machine", rateBdtPerKg: 730 },
  { group: "Machineries, Electronic, Car Accessories", item: "Moulde", rateBdtPerKg: 700 },
  { group: "Machineries, Electronic, Car Accessories", item: "Valve", rateBdtPerKg: 700 },
  { group: "Machineries, Electronic, Car Accessories", item: "Bearing", rateBdtPerKg: 700 },
  { group: "Machineries, Electronic, Car Accessories", item: "Transmission Shaft", rateBdtPerKg: 700 },
  { group: "Machineries, Electronic, Car Accessories", item: "Gear Box", rateBdtPerKg: 700 },
  { group: "Machineries, Electronic, Car Accessories", item: "Pully", rateBdtPerKg: 700 },
  { group: "Machineries, Electronic, Car Accessories", item: "Metal Gasket", rateBdtPerKg: 700 },
  { group: "Machineries, Electronic, Car Accessories", item: "Flange", rateBdtPerKg: 700 },
  { group: "Machineries, Electronic, Car Accessories", item: "Mechanical Seal", rateBdtPerKg: 700 },
  { group: "Machineries, Electronic, Car Accessories", item: "Machinery Parts", rateBdtPerKg: 700 },
  { group: "Machineries, Electronic, Car Accessories", item: "Motor", rateBdtPerKg: 700 },
  { group: "Machineries, Electronic, Car Accessories", item: "Spark Plug", rateBdtPerKg: 730 },
  { group: "Machineries, Electronic, Car Accessories", item: "Car Audio Amplifier", rateBdtPerKg: 730 },
  { group: "Machineries, Electronic, Car Accessories", item: "Audio Amplifier", rateBdtPerKg: 730 },
  { group: "Machineries, Electronic, Car Accessories", item: "Fire Alarm Parts", rateBdtPerKg: 730 },
  { group: "Machineries, Electronic, Car Accessories", item: "Electric Parts Capacitor", rateBdtPerKg: 730 },
  { group: "Machineries, Electronic, Car Accessories", item: "Electric Parts Resistor", rateBdtPerKg: 730 },
  { group: "Machineries, Electronic, Car Accessories", item: "Relay", rateBdtPerKg: 730 },
  { group: "Machineries, Electronic, Car Accessories", item: "Connector", rateBdtPerKg: 730 },
  { group: "Machineries, Electronic, Car Accessories", item: "Switch Socket Parts", rateBdtPerKg: 730 },
  { group: "Machineries, Electronic, Car Accessories", item: "Pressure Switch", rateBdtPerKg: 730 },
  { group: "Machineries, Electronic, Car Accessories", item: "Busbar Trunking Parts", rateBdtPerKg: 730 },
  { group: "Machineries, Electronic, Car Accessories", item: "Cabinet/Box/Metal Frame", rateBdtPerKg: 730 },
  { group: "Machineries, Electronic, Car Accessories", item: "Electric Accessories", rateBdtPerKg: 730 },
  { group: "Machineries, Electronic, Car Accessories", item: "PCB Loaded Board", rateBdtPerKg: 1000 },
  { group: "Machineries, Electronic, Car Accessories", item: "Module Controller", rateBdtPerKg: 730 },
  { group: "Machineries, Electronic, Car Accessories", item: "Loaded PCB", rateBdtPerKg: 1000 },
  { group: "Machineries, Electronic, Car Accessories", item: "Switch Socket Parts", rateBdtPerKg: 800 },
  { group: "Machineries, Electronic, Car Accessories", item: "Extension Plug", rateBdtPerKg: 700 },
  { group: "Machineries, Electronic, Car Accessories", item: "Car Bumper Parts", rateBdtPerKg: 700 },
  { group: "Machineries, Electronic, Car Accessories", item: "Car Tyre", rateBdtPerKg: 750 },
  { group: "Machineries, Electronic, Car Accessories", item: "Electro Valve", rateBdtPerKg: 700 },
  { group: "Machineries, Electronic, Car Accessories", item: "Car Accessories", rateBdtPerKg: 700 },
  { group: "Machineries, Electronic, Car Accessories", item: "Auto Spare Parts", rateBdtPerKg: 700 },
  { group: "Machineries, Electronic, Car Accessories", item: "Bicycle Accessories", rateBdtPerKg: 700 },
  { group: "Machineries, Electronic, Car Accessories", item: "Measuring Instrument", rateBdtPerKg: 700 },
  { group: "Machineries, Electronic, Car Accessories", item: "Electric Part Sensor", rateBdtPerKg: 700 },
  { group: "Machineries, Electronic, Car Accessories", item: "Multimeter", rateBdtPerKg: 700 },
  { group: "Cosmetics And Skin Care Item", item: "Essential Oil", rateBdtPerKg: 1000 },
  { group: "Cosmetics And Skin Care Item", item: "Perfume", rateBdtPerKg: 1350 },
  { group: "Cosmetics And Skin Care Item", item: "Lipstick", rateBdtPerKg: 1200 },
  { group: "Cosmetics And Skin Care Item", item: "Serum/Toner", rateBdtPerKg: 1200 },
  { group: "Cosmetics And Skin Care Item", item: "Lip Preparation", rateBdtPerKg: 1200 },
  { group: "Cosmetics And Skin Care Item", item: "Eye Makeup Preparation", rateBdtPerKg: 1200 },
  { group: "Cosmetics And Skin Care Item", item: "Face Powder", rateBdtPerKg: 1100 },
  { group: "Cosmetics And Skin Care Item", item: "Body Moisturizer", rateBdtPerKg: 1180 },
  { group: "Cosmetics And Skin Care Item", item: "Make Up Box/Blusher/High Lighter", rateBdtPerKg: 1180 },
  { group: "Cosmetics And Skin Care Item", item: "Eye Shadow/Eye Liner", rateBdtPerKg: 1180 },
  { group: "Cosmetics And Skin Care Item", item: "Lip Gloss", rateBdtPerKg: 1180 },
  { group: "Cosmetics And Skin Care Item", item: "Foundation", rateBdtPerKg: 1180 },
  { group: "Cosmetics And Skin Care Item", item: "Beauty Make Up, Skin-Care (Inc. Suntan)", rateBdtPerKg: 1180 },
  { group: "Cosmetics And Skin Care Item", item: "Shampoo", rateBdtPerKg: 1180 },
  { group: "Cosmetics And Skin Care Item", item: "Conditioner", rateBdtPerKg: 1180 },
  { group: "Cosmetics And Skin Care Item", item: "Deodorant/Body Spray", rateBdtPerKg: 1180 },
  { group: "Cosmetics And Skin Care Item", item: "Soap and Organic Surface-Active Products In Bars, Facial Mask", rateBdtPerKg: 950 },
  { group: "Cosmetics And Skin Care Item", item: "Facial Mask", rateBdtPerKg: 1170 },
  { group: "Cosmetics And Skin Care Item", item: "Herbal Soap/Facewash/Bodywash/Gel/Cleanser", rateBdtPerKg: 1170 },
  { group: "Cosmetics And Skin Care Item", item: "Toner", rateBdtPerKg: 1170 },
  { group: "Cosmetics And Skin Care Item", item: "Face Mask", rateBdtPerKg: 1170 },
  { group: "Cosmetics And Skin Care Item", item: "Eye Lash", rateBdtPerKg: 1200 },
  { group: "Cosmetics And Skin Care Item", item: "Tooth Brush/Brush", rateBdtPerKg: 730 },
  { group: "Cosmetics And Skin Care Item", item: "Nail and Hair Accessories (without Liquid)", rateBdtPerKg: 750 },
  { group: "Mobile Accessories Item", item: "Screen Protector", rateBdtPerKg: 1400 },
  { group: "Mobile Accessories Item", item: "Mobile Display", rateBdtPerKg: 2800 },
  { group: "Mobile Accessories Item", item: "Mobile Cover", rateBdtPerKg: 880 },
  { group: "Mobile Accessories Item", item: "Wired Earphone", rateBdtPerKg: 780 },
  { group: "Mobile Accessories Item", item: "Bluetooth Earphone", rateBdtPerKg: 1000 },
  { group: "Stationery Item", item: "Diary", rateBdtPerKg: 750 },
  { group: "Stationery Item", item: "Adhesive Sticker/Tape", rateBdtPerKg: 750 },
  { group: "Stationery Item", item: "Stapler", rateBdtPerKg: 750 },
  { group: "Stationery Item", item: "Books (Printed)", rateBdtPerKg: 750 },
  { group: "Stationery Item", item: "Regular Pen", rateBdtPerKg: 1000 },
  { group: "Stationery Item", item: "Gel Pen", rateBdtPerKg: 1000 },
  { group: "Battery And Charger Accessories", item: "Adapter/ Power Brick/ Charging Head", rateBdtPerKg: 800 },
  { group: "Battery And Charger Accessories", item: "Battery Charger", rateBdtPerKg: 800 },
  { group: "Battery And Charger Accessories", item: "Camera Battery", rateBdtPerKg: 1400 },
  { group: "Battery And Charger Accessories", item: "Adaptor Accessories", rateBdtPerKg: 750 },
  { group: "Battery And Charger Accessories", item: "Battery Parts", rateBdtPerKg: 750 },
  { group: "Battery And Charger Accessories", item: "Battery", rateBdtPerKg: 1350 },
  { group: "Battery And Charger Accessories", item: "Power Bank", rateBdtPerKg: 1350 },
  { group: "Garments And Garments Accessories", item: "Catalogue", rateBdtPerKg: 700 },
  { group: "Garments And Garments Accessories", item: "Fabrics (Printed)", rateBdtPerKg: 720 },
  { group: "Garments And Garments Accessories", item: "Fabrics (Non Printed)", rateBdtPerKg: 720 },
  { group: "Garments And Garments Accessories", item: "Net Fabrics", rateBdtPerKg: 720 },
  { group: "Garments And Garments Accessories", item: "Fabrics Embroidered", rateBdtPerKg: 720 },
  { group: "Garments And Garments Accessories", item: "Artificial Leather with Fabrics", rateBdtPerKg: 780 },
  { group: "Garments And Garments Accessories", item: "Blanket Fabrics", rateBdtPerKg: 750 },
  { group: "Garments And Garments Accessories", item: "Knitting Needle", rateBdtPerKg: 920 },
  { group: "Garments And Garments Accessories", item: "Sewing Machine", rateBdtPerKg: 700 },
  { group: "Garments And Garments Accessories", item: "Mini Sewing Machine", rateBdtPerKg: 700 },
  { group: "Garments And Garments Accessories", item: "Sewing Needle", rateBdtPerKg: 900 },
  { group: "Watches And Watch Accessories", item: "Smart Watch", rateBdtPerKg: 1350 },
  { group: "Watches And Watch Accessories", item: "Baby Watch", rateBdtPerKg: 1250 },
  { group: "Watches And Watch Accessories", item: "Watch Plastic", rateBdtPerKg: 1150 },
  { group: "Watches And Watch Accessories", item: "Watch Metal", rateBdtPerKg: 1150 },
  { group: "Watches And Watch Accessories", item: "Watch Part", rateBdtPerKg: 1100 },
  { group: "Computer Parts And Accessories", item: "Printing Ink", rateBdtPerKg: 1200 },
  { group: "Computer Parts And Accessories", item: "Computer Printer (Without Toner/Cartridge)", rateBdtPerKg: 750 },
  { group: "Computer Parts And Accessories", item: "Toner Cartridge", rateBdtPerKg: 1150 },
  { group: "Computer Parts And Accessories", item: "Parts of Printer", rateBdtPerKg: 700 },
  { group: "Computer Parts And Accessories", item: "Thermal Printer", rateBdtPerKg: 900 },
  { group: "Computer Parts And Accessories", item: "Laptop", rateBdtPerKg: 2200 },
  { group: "Computer Parts And Accessories", item: "Barcode Scanner", rateBdtPerKg: 1100 },
  { group: "Computer Parts And Accessories", item: "Hard Disk Drive", rateBdtPerKg: 850 },
  { group: "Computer Parts And Accessories", item: "Computer Mother Board", rateBdtPerKg: 950 },
  { group: "Computer Parts And Accessories", item: "RAM", rateBdtPerKg: 1000 },
  { group: "Computer Parts And Accessories", item: "Graphics Card", rateBdtPerKg: 1400 },
  { group: "Computer Parts And Accessories", item: "Mouse", rateBdtPerKg: 700 },
  { group: "Computer Parts And Accessories", item: "Mouse Pad", rateBdtPerKg: 750 },
  { group: "Computer Parts And Accessories", item: "Magic Key Board", rateBdtPerKg: 700 },
  { group: "Computer Parts And Accessories", item: "Keyboard", rateBdtPerKg: 700 },
  { group: "Computer Parts And Accessories", item: "Power Supply", rateBdtPerKg: 750 },
  { group: "Computer Parts And Accessories", item: "Microphone", rateBdtPerKg: 750 },
  { group: "Computer Parts And Accessories", item: "Speaker", rateBdtPerKg: 750 },
  { group: "Computer Parts And Accessories", item: "Headphone", rateBdtPerKg: 750 },
  { group: "Computer Parts And Accessories", item: "Monitor Up to 5''", rateBdtPerKg: 1000 },
  { group: "Computer Parts And Accessories", item: "Monitor 6-15''", rateBdtPerKg: 1200 },
  { group: "Computer Parts And Accessories", item: "Monitor 16-30''", rateBdtPerKg: 1200 },
  { group: "Computer Parts And Accessories", item: "Set Top Box", rateBdtPerKg: 780 },
  { group: "Computer Parts And Accessories", item: "Onu", rateBdtPerKg: 780 },
  { group: "Computer Parts And Accessories", item: "Router", rateBdtPerKg: 780 },
  { group: "Computer Parts And Accessories", item: "USB Cable", rateBdtPerKg: 750 },
  { group: "Computer Parts And Accessories", item: "Cable With Connector", rateBdtPerKg: 750 },
  { group: "Computer Parts And Accessories", item: "LED Projector", rateBdtPerKg: 1000 },
  { group: "Camera and Camera Accessories", item: "IP Camera", rateBdtPerKg: 750 },
  { group: "Camera and Camera Accessories", item: "CC Camera", rateBdtPerKg: 750 },
  { group: "Camera and Camera Accessories", item: "Action Camera", rateBdtPerKg: 1200 },
  { group: "Camera and Camera Accessories", item: "Digital Camera", rateBdtPerKg: 2000 },
  { group: "Camera and Camera Accessories", item: "Digital Video Camera", rateBdtPerKg: 1600 },
  { group: "Food Items", item: "Mushroom", rateBdtPerKg: 1250 },
  { group: "Food Items", item: "Green Tea", rateBdtPerKg: 1200 },
  { group: "Food Items", item: "Black Tea", rateBdtPerKg: 1200 },
  { group: "Food Items", item: "Gym Protein Powder", rateBdtPerKg: 1300 },
  { group: "Food Items", item: "Natural Food Supplement", rateBdtPerKg: 1300 },
  { group: "Food Items", item: "Pet Food", rateBdtPerKg: 1200 },
  { group: "Food Items", item: "Chocolate Items", rateBdtPerKg: 1250 },
  { group: "Food Items", item: "Dry Natural Food", rateBdtPerKg: 1250 },
  { group: "Sunglass And Accessories", item: "Lens", rateBdtPerKg: 750 },
  { group: "Sunglass And Accessories", item: "Sunglass Parts", rateBdtPerKg: 780 },
  { group: "Sunglass And Accessories", item: "Sunglass", rateBdtPerKg: 2800 },
  { group: "Medical Accessories", item: "Mouthwash", rateBdtPerKg: 1000 },
  { group: "Medical Accessories", item: "Test Kit (Pregnancy)", rateBdtPerKg: 1100 },
  { group: "Medical Accessories", item: "Nebulizer with battery", rateBdtPerKg: 1000 },
  { group: "Medical Accessories", item: "Nebulizer without battery", rateBdtPerKg: 750 },
  { group: "Medical Accessories", item: "Hand Gloves", rateBdtPerKg: 750 },
  { group: "Medical Accessories", item: "Breast Pump", rateBdtPerKg: 750 },
  { group: "Medical Accessories", item: "Thermometer", rateBdtPerKg: 750 },
  { group: "TV And TV Parts", item: "TV Brand 14-21\" TO TV Brand 32-49\"", rateBdtPerKg: 1500 },
  { group: "TV And TV Parts", item: "TV Brand 50-55\" and Above", rateBdtPerKg: 1500 },
  { group: "TV And TV Parts", item: "TV Parts (PCB Loaded)", rateBdtPerKg: 880 },
  { group: "TV And TV Parts", item: "TV Parts", rateBdtPerKg: 750 },
  { group: "TV And TV Parts", item: "TV Remote", rateBdtPerKg: 800 },
  { group: "Other's Various Items", item: "Seeds", rateBdtPerKg: 900 },
  { group: "Other's Various Items", item: "Umbrella", rateBdtPerKg: 750 },
  { group: "Other's Various Items", item: "Jewelry, Ornaments", rateBdtPerKg: 750 },
  { group: "Other's Various Items", item: "Powder", rateBdtPerKg: 1100 },
  { group: "Other's Various Items", item: "Slingshot", rateBdtPerKg: 970 },
  { group: "Other's Various Items", item: "Slingshot (Without Battery & Liquid)", rateBdtPerKg: 750 },
  { group: "Other's Various Items", item: "Safety Helmet", rateBdtPerKg: 750 },
  { group: "Other's Various Items", item: "Wig/Artificial Hair", rateBdtPerKg: 800 },
  { group: "Other's Various Items", item: "Baby Carrier", rateBdtPerKg: 780 },
  { group: "Other's Various Items", item: "Musical Accessories", rateBdtPerKg: 750 },
  { group: "Other's Various Items", item: "Playing Games (eg. chess, Ludo)", rateBdtPerKg: 750 },
  { group: "Other's Various Items", item: "Mini Guitar", rateBdtPerKg: 750 },
  { group: "Other's Various Items", item: "Parts of Furniture", rateBdtPerKg: 780 },
  { group: "Other's Various Items", item: "Toy Remote Control", rateBdtPerKg: 1000 },
  { group: "Other's Various Items", item: "Toy Without Remote & Battery", rateBdtPerKg: 750 },
  { group: "Other's Various Items", item: "Toy Puzzle", rateBdtPerKg: 750 },
  { group: "Other's Various Items", item: "Football", rateBdtPerKg: 750 },
  { group: "Other's Various Items", item: "Gym Equipment", rateBdtPerKg: 720 },
  { group: "Other's Various Items", item: "Sports Equipment", rateBdtPerKg: 720 },
  { group: "Other's Various Items", item: "Fishing Rod", rateBdtPerKg: 750 },
  { group: "Other's Various Items", item: "Fishing Hook", rateBdtPerKg: 750 },
  { group: "Other's Various Items", item: "Fishing Reel", rateBdtPerKg: 750 },
  { group: "Other's Various Items", item: "Tennis Ball/ Table Tennis Ball", rateBdtPerKg: 1000 },
  { group: "Other's Various Items", item: "Sleeping Mask", rateBdtPerKg: 800 },
  { group: "Other's Various Items", item: "Calculator (With Battery)", rateBdtPerKg: 950 },
  { group: "Other's Various Items", item: "Calculator (Without Battery)", rateBdtPerKg: 750 },
  { group: "Other's Various Items", item: "Bow And Arrows", rateBdtPerKg: 800 },
  { group: "Other's Various Items", item: "Glue", rateBdtPerKg: 1200 },
] as const;

export function findShippingTariffByItem(item: string): ShippingTariffItem | undefined {
  const key = normalizeTariffText(item);
  return SHIPPING_TARIFFS.find((tariff) => normalizeTariffText(tariff.item) === key);
}

export function listShippingTariffGroups(): string[] {
  return Array.from(new Set(SHIPPING_TARIFFS.map((tariff) => tariff.group)));
}

export function listShippingTariffsByGroup(group: string): ShippingTariffItem[] {
  const key = normalizeTariffText(group);
  return SHIPPING_TARIFFS.filter((tariff) => normalizeTariffText(tariff.group) === key);
}

function normalizeTariffText(value: string): string {
  return value.trim().toLowerCase().replace(/\s+/g, " ");
}
